export default class ANNOTATIONTYPES {
    public static readonly ANNOTATIONTYPE_USEPAIR = "ANNOTATIONTYPE_USEPAIR";
    public static readonly ANNOTATIONTYPE_USERANK = "ANNOTATIONTYPE_USERANK";
    public static readonly ANNOTATIONTYPE_USERANK_RELATIVE = "ANNOTATIONTYPE_USERANK_RELATIVE";
    public static readonly ANNOTATIONTYPE_USERANK_PAIR = "ANNOTATIONTYPE_USERANK_PAIR";
    public static readonly ANNOTATIONTYPE_WSSIM = "ANNOTATIONTYPE_WSSIM";
    public static readonly ANNOTATIONTYPE_LEXSUB = "ANNOTATIONTYPE_LEXSUB";
    public static readonly ANNOTATIONTYPE_SENTIMENT = "ANNOTATIONTYPE_SENTIMENT";
    public static readonly ANNOTATIONTYPE_CHOICE = "ANNOTATIONTYPE_CHOICE";


}